name: Convert Readme Links to CSV

on: 
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Get Urls and Push 
      run: |
        # grep for all text inside ()'s 
        # and again for any line that now starts with http
        # this will overwrite the old file
        grep -oP '\(\K[^\)]+' README.md | grep -E '^http' > urls.csv

        # add a ',' to the end of each line to make it an actual csv
        sed -i 's/$/\,/' urls.csv

        #commit to HEAD
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add urls.csv 
        git commit -m "generate batch readable list"
        git push
      shell: bash


